### ISSUE TITLE
WordPress error message when using WPForms PDF embeder

### ISSUE THREAD

**Issue by calvindebeverly** [breakfastco/embed-pdf-wpforms#1]
I acctivated this plugin and created a form. But WordPress had an issue with it. I could not continue with WordPress until I deactivated the plugin. In my administration email I recieved the following error message:

Error Details
=============
An error of type E_ERROR was caused in line 545 of the file /home1/ritakild/public_html/wp-content/plugins/embed-pdf-wpforms/includes/class-wpforms-field-pdf-viewer.php. Error message: Uncaught Error: Undefined constant WPForms_Field_PDF_Viewer::CHOICES_VERSION in /home1/ritakild/public_html/wp-content/plugins/embed-pdf-wpforms/includes/class-wpforms-field-pdf-viewer.php:545
Stack trace:
#0 /home1/ritakild/public_html/wp-includes/class-wp-hook.php(310): WPForms_Field_PDF_Viewer->enqueue_block_editor_assets('')
#1 /home1/ritakild/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 /home1/ritakild/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home1/ritakild/public_html/wp-admin/site-editor.php(154): do_action('enqueue_block_e...')
#4 {main}
  thrown

This needs to be corrected. 
Thank you.

**Comment by csalzano** [comment]
Are you using an old version? Line 545 of that file does not contain a reference to a constant CHOICES_VERSION: https://github.com/breakfastco/embed-pdf-wpforms/blob/main/includes/class-wpforms-field-pdf-viewer.php#L545

**Comment by calvindebeverly** [comment]
I downloaded the plugin about a week ago. If you have a newer version within that time span then I would be using an older version. The version of the plugin I hav installed is Version 1.0.0. Do I need to reinatall?

Also I do have another question. Is there anyway to get rid of the SUBMIT button that seems to be included with the WPForm. It is clickable and has nothing to do with your PDF embeder.

**Comment by csalzano** [comment]
Here's some JavaScript to disable the submit button: https://wpforms.com/developers/how-to-conditionally-show-the-submit-button/#q-can-i-just-disable-the-submit-button-until-all-fields-have-a-value

If you don't need a submit button, why are you using a form builder?

Download the latest version of this plugin https://github.com/breakfastco/embed-pdf-wpforms/archive/refs/heads/main.zip

The current version is 1.1.0. There is a "Releases" section on the project home page https://github.com/breakfastco/embed-pdf-wpforms

**Comment by calvindebeverly** [comment]
Okay it works beautifully. And with the code you suggested the Submit button is gone. Thank you so much!

If there was anything you might to improve the plugin I might humbly suggest that there also be a

[cid:b5fdca88-36f6-4c57-bfdb-a2657b12a671]

at the end of the PDF text so that the reader would not have to scroll back up to access these function.

But all in all REALLY well done. I commend you.

Have a great day!

Calvin De Beverly
________________________________
